baseurl: "/"
url: "https://dblp.org"

plugins:
    - jekyll-rdf

jekyll_rdf:
    path: "dblp_natanael.nt"
    default_template: "default.html"
    restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . FILTER regex(str(?resourceUri), \"https://dblp.org\")  }"
    class_template_mappings:
        "http://xmlns.com/foaf/0.1/Person": "person.html"
    instance_template_mappings:
        "http://example.org/simpsons/Abraham": "abraham.html"
